#SPDX-License-Identifier: MIT-0
# tasks file for roles/webserver

---
- name: Install Apache
  apt:
    name: "{{ apache_package_name }}"
    state: present
    update_cache: yes

- name: Ensure Apache service is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
